// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdM4LHHF-mZiWjExLmBqJPSdawSi9lNck',
    appId: '1:376377669660:web:00a880aea108b9e7b347d9',
    messagingSenderId: '376377669660',
    projectId: 'chat-application-630e8',
    authDomain: 'chat-application-630e8.firebaseapp.com',
    databaseURL: 'https://chat-application-630e8-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-630e8.firebasestorage.app',
    measurementId: 'G-53ET067SQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5bBEjIq4U6_dg530ewK6KM2G0taKOhs',
    appId: '1:376377669660:android:bb73c71c4d07b096b347d9',
    messagingSenderId: '376377669660',
    projectId: 'chat-application-630e8',
    databaseURL: 'https://chat-application-630e8-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-630e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJRuhtmrmJNDTvAJzG4M5YJZHItoaJ3E',
    appId: '1:376377669660:ios:04fb280e8a70363fb347d9',
    messagingSenderId: '376377669660',
    projectId: 'chat-application-630e8',
    databaseURL: 'https://chat-application-630e8-default-rtdb.firebaseio.com',
    storageBucket: 'chat-application-630e8.firebasestorage.app',
    iosClientId: '376377669660-h1cvjg2fqucah4dqo91c5l5dihm6ds3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
